# docker compose versions
version: '2'

# shared volumes
volumes:
  project:
  server_node_modules:
  worker_node_modules:
  app_node_modules:

services:
  # web app bundle build
  app:
    image: openneuro/app:${CRN_APP_TAG}
    command: bash -c "yarn install && yarn start"
    volumes:
      - ../openneuro/app:/srv/crn-app
      - app_node_modules:/srv/crn-app/node_modules
      - project:/srv/crn-app/dist

  # crn core (bids-core)
  core:
    volumes:
      - ../bids-core:/srv/bids-core
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data

  # crn node server
  server:
    command: bash -c "yarn install && node /srv/crn-server/index.js"
    volumes:
      - ../openneuro/server:/srv/crn-server
      - server_node_modules:/srv/crn-server/node_modules
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/crn-server/persistent

  worker:
    command: bash -c "yarn install && node /srv/crn-server/worker.js"
    volumes:
      - ../openneuro/server:/srv/crn-server
      - worker_node_modules:/srv/crn-server/node_modules
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/crn-server/persistent

  # nginx - static file serving and service proxy
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9876:80"
      - "8110:8110"
      - "8443:443"
